### ISSUE TITLE
Comment On rtosc API Use

### ISSUE THREAD

**Issue by fundamental** [xavriley/fast_osc#2]
I saw your blog post directing some traffic to rtosc's github page and I read:
> This meant keeping track of the size for each of the different types above and summing them for a given message. For strings (which vary in size) I took the bytesize() and then rounded up to the next power of two just to be safe.

rtosc actually takes care of this problem for you. Quoting the rtosc_message doc:
> When buffer is NULL, the function returns the size of the buffer required to store the message

There's no problem with your solution, I figured I'd just let you know about the library functionality.

**Comment by xavriley** [comment]
Thanks for letting me know - that makes sense now I come to think of it. I wasn't completely happy with the buffer sizing aspect when I wrote it but I wasn't aware of that functionality at the time.

I'll leave this issue open until I have time to rework the API.
